name: Annotation
on: push

jobs:
  log:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "::error::this is error message"
          echo "::warning::this is warning message"
          echo "::notice::this is notice message"
