name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'ell') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'ell') }}
