name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        if: ${{contains(github.run_id, 1)}} # This will run only if the run id contains 1
