name: Job Summary
on: push

jobs:
  log:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo ":- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo ":- second line" >> "${GITHUB_STEP_SUMMARY}"
