name: Share Job Data
on: push

jobs:
  first:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: generate
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.generate.outputs.result }}
  second:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [first]
    steps:
      - env:
          RESULT: ${{ needs.first.outputs.result }}
        run: echo "${RESULT}"
